### ISSUE TITLE
avr_loss is TOO strange???

### ISSUE THREAD

**Issue by ReloadProcz** [kohya-ss/musubi-tuner#158]
Firstly, I really appreciate this repo! I manually wrote some bash files in order to use this repo efficiently. And with lots of testing, it can finally run peacefully on my laptop (performance is BAD I think) and the speed is normal (about 6~8s/it?)

# Problem🤔

The biggest problem I met is that the value of avr_loss is REALLY, TOO STRANGE. Normally it SHOULD be lower than 1. However, I saw that the avr_loss is EVEN higher than 2 at some steps, and keep MUCH higher than 1 during the whole process. 

I did not test the final video output, so may I ask a question: Is that normal?

(Caching Latents and Text_Encoder_Outputs process is fine.)

# What I write to the train.sh bash file: 

```bash
../musubi-tuner/venv/bin/accelerate launch \
  --num_cpu_threads_per_process 1 \
  --mixed_precision bf16 \
  ../musubi-tuner/hv_train_network.py \
  --dit ../models/transformers/mp_rank_00_model_states_fp8.pt \
  --dataset_config ./dataset.toml \
  --sage_attn \
  --split_attn \
  --mixed_precision bf16 \
  --blocks_to_swap 36 \
  --optimizer_type adamw8bit \
  --lr_scheduler cosine_with_restarts \
  --lr_scheduler_num_cycles 10 \
  --max_grad_norm 0.3 \
  --scale_weight_norms 1.0 \
  --network_dropout 0.1 \
  --learning_rate 1e-3 \
  --gradient_checkpointing \
  --max_data_loader_n_workers 2 \
  --persistent_data_loader_workers \
  --network_module networks.lora \
  --network_args "loraplus_lr_ratio=4" "exclude_patterns=[r'.single_blocks.']" \
  --optimizer_args betas=0.9,0.99 weight_decay=0.05 eps=1e-8 \
  --network_dim 32 \
  --timestep_sampling shift \
  --discrete_flow_shift 7.0 \
  --max_train_epochs 20 \
  --save_every_n_epochs 1 \
  --seed 114514 \
  --output_dir ../outputs \
  --output_name test1 \
  --logging_dir ../logs/test1/
```

# The dataset.toml:

```toml
# general configurations
[general]
resolution = [960, 544] 
caption_extension = ".txt" 
batch_size = 1 
num_repeats = 1 
enable_bucket = true 
bucket_no_upscale = false 

### Image Dataset

# sample image dataset with caption text files
[[datasets]]
image_directory = "../datasets/image_dir/"
caption_extension = ".txt" 
resolution = [384, 288] 
batch_size = 1
num_repeats = 1 
enable_bucket = true
bucket_no_upscale = true 
cache_directory = "../cache/vae" 
# Video Dataset
[[datasets]]
video_directory = "../datasets/video_dir/"
cache_directory = "../cache/txt" 
target_frames = [1, 25, 45]
resolution= [216, 384]
frame_extraction = "head"
```

I'll be appreciate if u can solve my problem. Thank u again!!!😙
